---
# root work
- block:
    - name: Install the 'Development' package group
      yum:
        name: "@development"
        state: present

    - name: Install deps for Bazel
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc-c++
        - glibc-static
        - libstdc++-static

    - name: Add copr repo for bazel
      yum_repository:
        name: copr
        description: copr for bazel
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/pubkey.gpg
        baseurl: https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/epel-7-$basearch/

    - name: Install bazel
      package:
        name: bazel
        state: present
  become: true
  become_user: root

# init as user
- name: Run bazel to init it.
  command: >
    bazel help
